spring:
  application:
    name: auth-service

server:
  port: 8081


security:
  user:
    name: root
    password: password
  oauth2:
    client:
      client-id: test-purpose-client-id #todo change later
      client-secret: secret #todo change later


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: TRACE