spring:
  application:
    name: auth-service


security:
  user:
    name: root
    password: password
  oauth2:
    client:
      client-id: acme
      client-secret: secret


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: TRACE